Main menu criado
duardoqueiroz/Street-Fight-Arapiraca-Editon pull request #20
Opened 2021-05-31 21:53 UTC by duardoqueiroz

- menu principal criado;
- quando o jogador aperta enter, a cena muda;
- som de fundo adicionado
![main menu](https://user-images.githubusercontent.com/83377894/120244687-4d459280-c241-11eb-815e-48d000575bae.gif)

2021-05-31 23:17 UTC, Z1wolfmaster1 commented on assets/scripts/controller/KeyboardController.ts
> +const { ccclass, property } = cc._decorator;
Se não estiver usando o decorator property, retire das importações

2021-05-31 23:24 UTC, Z1wolfmaster1 requested changes

2021-05-31 23:24 UTC, Z1wolfmaster1 commented on assets/scripts/controller/MainmenuKeyboardController.ts
> +    protected onKeyUp(event: cc.Event.EventKeyboard) {
Não se cria função que não faz nada. Se não estiver usando agora, remova e adicione só quando precisar

2021-05-31 23:54 UTC, duardoqueiroz commented on assets/scripts/controller/KeyboardController.ts
> +const { ccclass, property } = cc._decorator;
corrigido
3f61243457784014f59d021722281db640a9f98e

2021-05-31 23:54 UTC, duardoqueiroz commented on assets/scripts/controller/MainmenuKeyboardController.ts
> +    protected onKeyUp(event: cc.Event.EventKeyboard) {
corrigido
3f61243457784014f59d021722281db640a9f98e

2021-06-01 01:26 UTC, sandenson requested changes

2021-06-01 01:26 UTC, sandenson commented on assets/scripts/controller/MMKeyboardController.ts
> +import KeyboardController from "./KeyboardController";
O nome do arquivo deve ser igual ao da classe.

2021-06-01 01:26 UTC, sandenson commented on assets/scripts/controller/MMKeyboardController.ts
> +export default class MainmenuKeyboardController extends KeyboardController {
```suggestion
export default class MainMenuKeyboardController extends KeyboardController {
```

2021-06-01 19:19 UTC, duardoqueiroz commented on assets/scripts/controller/MMKeyboardController.ts
> +export default class MainmenuKeyboardController extends KeyboardController {
corrigido
18dbd62494b7adc94e7265769133d2f7eacb6552

2021-06-05 20:14 UTC, sandenson requested changes

2021-06-05 20:14 UTC, sandenson commented on assets/scripts/controller/MainmenuKeyboardController.ts
> +import KeyboardController from "./KeyboardController";
Renomeem esse arquivo pra MainMenuKeyboardController. Atenção aos nomes, galera.

2021-06-05 20:14 UTC, sandenson commented on assets/scripts/controller/MainmenuKeyboardController.ts
> +export default class MainmenuKeyboardController extends KeyboardController {
Mudem aqui também.

```suggestion
export default class MainMenuKeyboardController extends KeyboardController {
```

2021-06-06 22:14 UTC, sandenson commented on assets/scripts/controller/MMKeyboardController.ts
> +export default class MainmenuKeyboardController extends KeyboardController {
Ainda tá errado

2021-06-06 22:16 UTC, sandenson requested changes
Ainda tem coisas faltando.

2021-06-07 18:54 UTC, sandenson approved these changes

2021-06-07 19:12 UTC, merged