Cutscene1
duardoqueiroz/Street-Fight-Arapiraca-Editon pull request #21
Opened 2021-06-03 18:09 UTC by guilherme-gjv

- Adicionada a cutscene inicial 

1. Adicionado arquivo de áudio;
2. Adicionado Animações;
3. Adicionado Script para a transição da cutscene ao menu principal por meio de animation event.

https://user-images.githubusercontent.com/83377948/120691890-6b97d200-c47d-11eb-8318-231415550d6c.mp4

2021-06-05 20:28 UTC, sandenson reviewed
Apaguem os espaços dos nomes de todos os arquivos que tiverem espaços.

2021-06-05 20:28 UTC, sandenson commented on assets/Textures/arena_selec/arapimapa (1).png.meta
> +{
Ow, tirem esse " (1)" do nome do arquivo. Isso pode dar bronca.

2021-06-05 20:28 UTC, sandenson commented on assets/Textures/arena_selec/pino vermelho di vdd.png.meta
> +{
Tirem os espaços desse título aqui também. Não ponham espaços. Honestamente, eu não sei se isso dá bronca na Cocos, mas na Unreal dá.

2021-06-05 20:28 UTC, sandenson commented on assets/Textures/character/naruto/naruto_down/0 (1).png.meta
> +{
Tirem o espaço do nome desse arquivo, também.

2021-06-05 20:28 UTC, sandenson commented on assets/textures/menu/arapimapa (1).png.meta
>  {
Aqui também.

2021-06-05 20:31 UTC, sandenson requested changes
Tirem os espaços dos nomes de arquivos que contêm espaços.

2021-06-05 23:06 UTC, guilherme-gjv commented on assets/textures/menu/arapimapa (1).png.meta
>  {
Done. :+1:

2021-06-06 22:21 UTC, sandenson approved these changes
Aprovado, dotôres 😎👍

2021-06-06 22:21 UTC, sandenson commented on assets/textures/menu/arapimapa (1).png.meta
>  {
Bela pica 😎👍

2021-06-07 19:11 UTC, merged